### ISSUE TITLE
Preferably different icons for Shuffle and Randomize

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#213] opened 2022-01-25 14:04 UTC
<img width="1144" alt="Screen Shot 2022-01-25 at 14 44 10" src="https://user-images.githubusercontent.com/62497891/150991399-80e36a9f-3d49-4fc5-bed5-9e6b572a0480.png">

**Comment by kode54** [comment] 2022-01-26 02:19
Duplicate of #129

**Closed** 2022-01-26 02:19 UTC
Labels: duplicate
