### ISSUE TITLE
Crash, conflict with QuickTime

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#182] opened 2021-11-29 15:20 UTC
- macOS version: 12.0.1 (21A559)
- Cog version: 1625 (1625-g57726629)

[Archive.zip](https://github.com/losnoco/Cog/files/7619104/Archive.zip)

**Comment by kode54** [comment] 2021-12-01 04:01
I literally don't know how to use these. Reproduction steps are more useful.

Also, I literally can't support Intel Macs running anything newer than Big Sur, as I will never own a new enough Intel Mac to actually run Monterey. No, I don't want one, either.

**Comment by Oleg-Chashko** [comment] 2021-12-01 11:34
- MacBook Pro (Retina, 13-inch, Early 2015)

Reproduction steps are more useful:
1. I start the song in the Cog player.
2. I start the QuickTime player.
3. In the QuickTime player I choose: New Audio Recording.
<img width="223" alt="Screen Shot 2021-12-01 at 12 13 24" src="https://user-images.githubusercontent.com/62497891/144225175-2f7de286-c9f5-46a8-a339-3fbdaf9b41c7.png">
4. Crash.

P.S.: As I think the conflict occurs with the choice: Audio output device. And this is directly related to #181.
When there is more than one "Audio output device" the player has problems with this.

**Comment by kode54** [comment] 2021-12-01 21:00
Why are you closing the issue? It seems to be an issue for you. I just don't have an environment that can reproduce it.

**Comment by Oleg-Chashko** [comment] 2021-12-02 10:27
Why are you closing the issue?
These two problems are interconnected, with: Clicks and digital noise after rewinding or switching songs. #181
Closed the topic so as not to duplicate. 
Thank you for the application, I was especially pleased with the Mini Player mode. 
Thank you.

**Comment by Oleg-Chashko** [comment] 2021-12-22 13:35
Version 1638 (1638-g7da3324e)

https://user-images.githubusercontent.com/62497891/147100877-d7024fb1-7d08-4606-a059-29356cc897cd.mp4

**Comment by kode54** [comment] 2021-12-24 09:06
What audio device are you using? What is configured for output in Cog? What is QuickTime configured to record from? Is QuickTime recording at the time, or is it stopped?

**Comment by Oleg-Chashko** [comment] 2021-12-24 10:53
> What audio device are you using? 
What is configured for output in Cog? 
What is QuickTime configured to record from? 
Is QuickTime recording at the time, or is it stopped?

**What audio device are you using?** 
- Sennheiser HD4.40BT
![Sennheiser HD4 40BT](https://user-images.githubusercontent.com/62497891/147346090-48a8d4e8-7e90-44ea-a494-56429a0f9e91.jpg)

**What is configured for output in Cog?**
- System Default Device
<img width="584" alt="Screen Shot 2021-12-24 at 11 38 32" src="https://user-images.githubusercontent.com/62497891/147346268-c164e017-dea0-47b2-a82d-a1a4d166d44e.png">

**What is QuickTime configured to record from?**
- Sennheiser HD4.40BT
<img width="581" alt="Screen Shot 2021-12-24 at 11 36 11" src="https://user-images.githubusercontent.com/62497891/147346365-e7ca83d4-5ff6-4252-bbbe-05b0d8b51132.png">

**Is QuickTime recording at the time, or is it stopped?**
- Stopped

https://user-images.githubusercontent.com/62497891/147346569-57f7ef7f-4d04-43ef-bfcf-c7bd458f49e3.mp4

**Comment by kode54** [comment] 2021-12-25 10:12
It must be the sound format of your specific Bluetooth device when switched into communications mode. Please check Audio MIDI Setup, and report what formats the output device claims to support.

I set Cog to output to my AirPods Pro, and tested playback both when playing, and when opening a new Audio Recording in QuickTime Player, and all it managed to do was murder the sound output quality when it switched the AirPods into communication mode. Then when I quit QuickTime Player, it eventually switched back to playback mode. No crash.

Oh, I see. It's because I request what format the output device wants and resample to it. I should be forcing a playback quality and let AudioToolbox resample for me.

**Comment by Oleg-Chashko** [comment] 2021-12-25 10:36
- Please check Audio MIDI Setup, and report what formats the output device claims to support.

![Screen_2](https://user-images.githubusercontent.com/62497891/147383172-9e58e50c-1e34-4374-b5f3-499ec090629b.gif)
![Screen](https://user-images.githubusercontent.com/62497891/147383177-a6807348-b67a-4553-9a21-0800c514cb31.gif)

**Comment by kode54** [comment] 2021-12-26 01:04
This should be fixed by 1648, but don't be surprised if the sound output doesn't sound right after you stop recording with QuickTime. Not crashing is the best it's going to get for now.

**Comment by Oleg-Chashko** [comment] 2021-12-26 02:35
I closed the topic, there is no conflict with. Thank you!

**Closed** 2021-12-26 02:35 UTC
